export * from './ErrorPage'
export * from './ForgotPassword'
export * from './Login'
export * from './Home'
export * from './Dashboard'
export * from './Devices';
export * from './Service';
export * from './CapSo';
export * from './Report';
export * from './Account';
export * from './Role';
export * from './History';